name: Sync and Trigger Render Deployment

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Verify Repository Sync
        run: |
          echo "Repository is already synced by the push event."
          echo "Render will auto-deploy if connected to this branch."