# .github/workflows/build-and-deploy.yml

name: Build Mentat Flask App

# Trigger the workflow on push to main branch or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Install dependencies needed for the build script
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      # Run the build script
      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      # Configure git (needed for any git operations in the script)
      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Add and commit generated files
      - name: Commit generated files
        run: |
          cd mentat-flask-app
          git add .
          git commit -m "Generate project files from build script" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Verify the build
      - name: Verify build
        run: |
          cd mentat-flask-app
          ls -la
          cat requirements.txt

    env:
      # Using the default GitHub token
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}