cd aider-website
mkdir -p .github/workflows
cat << 'EOF' > .github/workflows/push-to-render.yml
name: Push to GitHub for Render Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
EOF
git add .github/workflows/push-to-render.yml
git commit -m "Add GitHub Actions workflow for Render deployment"
